name = "4Pack5"
author = ":3"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31aaa8a32191a7b26e94421ce20e295437339e577a4dc16ce9c674ccfc471834"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.212"
unsup = "1.2.0-pre3"

[options]
acceptable-game-versions = ["1.21", "1.21.0"]
datapack-folder = "./config/openloader/packs"
