name = "4Pack5"
author = ":3"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f38a71f57601edcc66f618fa1306c964c7d78574ae5df06996e7ce7c11bf9614"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.212"

[options]
acceptable-game-versions = ["1.21", "1.21.0"]
datapack-folder = "./config/openloader/packs"
