name = "4Pack5"
author = ":3"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91666071083ed4464106ed7a640e8ce4d50aba9107f10f12fc69acfb466f39ce"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.212"

[options]
acceptable-game-versions = ["1.21", "1.21.0"]
datapack-folder = "./config/openloader/packs"
