name = "4Pack5"
author = ":3"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4123ea4d62fffcef6a2cede336bad7a61fffdf9a4e090260cc3f8d8c487b0405"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.212"
unsup = "1.2.0-pre3"

[options]
acceptable-game-versions = ["1.21", "1.21.0"]
datapack-folder = "./config/openloader/packs"
