# Shaders
[flavor_groups.shaders]
name = "Shaders"
description = "Choose with shader related mods you want to have"
side = "client"
[[flavor_groups.shaders.choices]]
id = "no_shaders"
name = "None"
description = "No shader mods"
[[flavor_groups.shaders.choices]]
id = "base_shaders"
name = "Iris"
description = "Iris + Iris compat mods"
[[flavor_groups.shaders.choices]]
id = "euphoria_shaders"
name = "Euphoria"
description = "Iris, Iris compat mods along with Euphoria and Complementary"

[metafile.iris]
flavors = ["base_shaders", "euphoria_shaders"]
[metafile.colorwheel]
flavors = ["base_shaders", "euphoria_shaders"]
[metafile.colorwheel-patcher]
flavors = ["base_shaders", "euphoria_shaders"]
[metafile.euphoria-patches]
flavors = "euphoria_shaders"
[metafile.complementary-reimagined]
flavors = "euphoria_shaders"

# Mapping
[flavor_groups.mapping]
name = "Mapping Mods"
description = "Your choice of mapping mod for the server\n<b>Journeymap is highly recommended.</b>"
[[flavor_groups.mapping.choices]]
id = "journey"
name = "Journeymap"
description = "JourneyMap & MapFrontiers."
[[flavor_groups.mapping.choices]]
id = "webmap"
name = "JM + Web Map"
description = "JourneyMap along with its web map addon, letting you have your map open in a browser."
[[flavor_groups.mapping.choices]]
id = "xaeros"
name = "Xaero's Map"
description = "Xaero's Minimap + Worldmap. Will not have proper support compared to JM, but its here if you want it I guess."

[metafile.journeymap]
flavors = ["journey", "webmap"]
[metafile.mapfrontiers]
flavors = ["journey", "webmap"]
[metafile.journeymap-web-map]
flavors = "webmap"
[metafile.xaeros-minimap]
flavors = "xaeros"
[metafile.xaeros-world-map]
flavors = "xaeros"