[flavor_groups.distant_horizons]
name = "Distant Horizons"
side = "client"
description = "LOD Rendering mod, will use more ram than without (even if disabled?)"
choices = ["distant_horizons_off", "distant_horizons_on"]

[metafile.distanthorizons]
flavors = "distant_horizons_on"